name: 'Yarn/Node Cache w/ Working Dir'
author: 'zach-hill'
description: '1-liner to cache yarn and node_modules, with env variable to set working directory'
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
